// Generated by scripts/build-pages.mjs. Keys here are visible to every visitor.
window.SPARK_CONFIG = {
  "mode": "static",
  "region": "us-en",
  "xaiModel": "",
  "xaiChatModel": "",
  "xaiKey": "",
  "keenableKey": "keen_n5ap75mjaf_b6324ab074976c3580a4fad3c63eb8dc5692ab0a18aa425f949860665bbf2bff"
};
