// Builds the static GitHub Pages version of Spark into dist/.
//
// The browser calls Keenable and xAI directly, so the keys from .env are written into
// dist/spark-config.js and are PUBLIC to anyone who visits the site. Pass --no-keys to
// publish without them (search still works via Keenable's keyless endpoint; AI is off).
import fs from 'node:fs';
import path from 'node:path';
import { config, ROOT } from '../server/config.js';

const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
const siteUrl = (process.env.PAGES_URL || pkg.homepage || '').replace(/\/?$/, '/');
const withKeys = !process.argv.includes('--no-keys');
const out = path.join(ROOT, 'dist');

fs.rmSync(out, { recursive: true, force: true });
fs.cpSync(path.join(ROOT, 'public'), out, { recursive: true });

const siteConfig = {
  mode: 'static',
  region: config.region,
  xaiModel: config.xai.model,
  xaiChatModel: config.xai.chatModel,
  xaiKey: withKeys ? config.xai.apiKey : '',
  keenableKey: withKeys ? config.keenable.apiKey : '',
};
fs.writeFileSync(
  path.join(out, 'spark-config.js'),
  `// Generated by scripts/build-pages.mjs. Keys here are visible to every visitor.\nwindow.SPARK_CONFIG = ${JSON.stringify(siteConfig, null, 2)};\n`
);

// GitHub Pages serves 404.html for unknown paths; the app routes from the URL itself.
fs.copyFileSync(path.join(out, 'index.html'), path.join(out, '404.html'));
fs.writeFileSync(path.join(out, '.nojekyll'), '');
fs.writeFileSync(
  path.join(out, 'opensearch.xml'),
  `<?xml version="1.0" encoding="UTF-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
  <ShortName>Spark</ShortName>
  <Description>Search the web with Spark</Description>
  <InputEncoding>UTF-8</InputEncoding>
  <Image width="32" height="32" type="image/png">${siteUrl}assets/favicon-32.png</Image>
  <Url type="text/html" method="get" template="${siteUrl}?q={searchTerms}"/>
</OpenSearchDescription>
`
);

console.log(`Built static site in dist/ for ${siteUrl}`);
console.log(`  Grok AI:  ${siteConfig.xaiKey ? 'on (key included — public)' : 'off (no xAI key)'}`);
console.log(`  Keenable: ${siteConfig.keenableKey ? 'API key included (public)' : 'keyless public endpoint'}`);
